### ISSUE TITLE
xs size

### ISSUE THREAD

**Issue by BaniGrisson** [anatoliygatt/numeric-stepper#35]
It would be appreciated if the size was customizable or there was a xs zise

**Comment by anatoliygatt** [comment]
Hi @BaniGrisson.

Do you mind sharing your use case? The `sm` size is quite small and I believe that providing an even smaller size would hit the component's usability on both desktop and mobile.

**Comment by anatoliygatt** [comment]
@BaniGrisson Just FYI, I'm closing this one.

**Comment by BaniGrisson** [comment]
> Hi @BaniGrisson.
> 
> Do you mind sharing your use case? The `sm` size is quite small and I believe that providing an even smaller size would hit the component's usability on both desktop and mobile.

The smallest size has a width of almost 180px. That's half the width of some phone screens.
The smallest size has a height of 74px. That's more than three lines of text. So to use a label that matches component's size I'd have to use a huge font size.

Not to mention that it looks huge in comparison with normal switches.

I get that it can't be as small as a normal switch, but I think half the size should be completely fine.

Another solution would be to just add a prop exposing size settings. Which would be great.

Anyways, amazing component either way. Wouldn't take the time to write otherwise. Thanks for your work!!

**Comment by jhonnybail** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
kgborland, @premmind, @xhad, @javais, @emmajam, @ManofDiligence, @aditya-singh9, @robertlcs, @joel-jaimon, @zzz157, @cryptoenthusiast0x2021, @nodeicode, @sanqima, @hn2, @guihongwan, @JasonMcz, @cometlj, @LeeAndrew14, @rodolfobandeira, @cagix, @ramonberrutti, @solimander, @jankremlacek, @crashcrypto, @tommy-ca, @jellydisc, @shih-liang, @JAYQ1998, @ioribrn, @soardex, @ejcer, @simontech, @rexliu0715, @rootsher, @Obooman, @DantasBeyer, @LVtomatoJ, @auroralabs, @osdio, @xspurs, @sinamoradi, @Nigh-ctrl, @HasanRoknabady, @gwhagerty, @azeem110201, @Aman-zishan, @b1u3h4t, @naszam, @archived-m, @git-zhoujunyuabdllhbyrktr, @GreatGreatGreg, @thryec, @Buooy, @sleazybheezy, @WoonchanCho, @tuchang, @metasimian, @er1c-zh, @amirali, @couturecraigj, @ethrdev, @cmarshall108, @arianxesl, @charloco, @Bahubaligray1, @NerdyDave2017, @gaspardip, @matichewer, @Fineas, @wilsonfonseca, @AuruTus, @syedMohib44, @Link14349, @AlexMuzzz, @Vimalraj571, @jxnclzl, @akuligowski9, @titan-web, @rosspeili, @AllenCoder, @hixio-mh, @kisslove, @hastebrot, @anakornk, @Araraki, @hzitoun, @vishwak1002, @pengxiaohua, @carlchang, @EunsungKoh, @MyatWatyeeHnin, @falkorsmaug, @ismail9k, @tyfhxn, @raiyning, @svbnbyrk, @ytw0728, @Aopodo, @HerrBertling
